version: '3.8'

services:
  api:
    image: api:develop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    container_name: samphran-line-api
    volumes:
      - ./public:/usr/src/app/public
